import assert from 'node:assert/strict';
import { createColorSearch } from '../domain/color-search.ts';
import { DEMO_CODE, demoReducer, filterRecords, initialDemoState } from './demo-state.ts';

let state = initialDemoState();
state = demoReducer(state, { type: 'email', value: 'color-check@example.invalid' });
state = demoReducer(state, { type: 'submit-email' });
state = demoReducer(state, { type: 'code', value: DEMO_CODE });
state = demoReducer(state, { type: 'verify' });
state = demoReducer(state, { type: 'start-record' });
state = demoReducer(state, { type: 'use-photo' });
state = demoReducer(state, { type: 'continue-photo' });
for (let i = 0; i < 4 && state.active_job; i++) state = demoReducer(state, { type: 'tick-processing', jobId: state.active_job.job_id, inputRevision: state.active_job.input_revision });
state = demoReducer(state, { type: 'confirm', value: true });
state = demoReducer(state, { type: 'continue-compare' });
state = demoReducer(state, { type: 'save' });
assert.ok(state.save_attempt);
state = demoReducer(state, { type: 'save-result', operationId: state.save_attempt.operation_id, outcome: 'success' });
const source = state.records[0];
assert.ok(source);
const record = (id, favorite = true, date = '2026-09-12', tag = '산책') => ({ ...source, id,
  fields: { ...source.fields, is_favorite: favorite, diary_date: date, semantic_tags: [tag], mood_tags: [] },
  color_tags: [{ hex: '#5D9665', rgb: [93, 150, 101], weight: 0.06 }, { hex: '#609867', rgb: [96, 152, 103], weight: 0.08 }, { hex: '#FFFFFF', rgb: [255, 255, 255], weight: 0.86 }],
});
const records = [record('both'), record('not-favorite', false), record('old', true, '2026-09-01'), record('other-tag', true, '2026-09-12', '카페'), { ...record('no-palette'), color_tags: [] }];
const filter = { start_date: '2026-09-10', end_date: '2026-09-14', semantic_tag: '산책', favorite_only: true, color: createColorSearch('#5D9665') };
assert.deepEqual(filterRecords(records, filter).map(r => r.id), ['both'], 'similar 6% and 8% colors aggregate and combine with every existing filter');
assert.deepEqual(filterRecords(records, { ...filter, color: { ...filter.color, minWeight: 0.25 } }), [], '25% excludes a 14% palette');
const snapshot = JSON.stringify(records);
state = demoReducer({ ...state, route: 'book', records, book_filter: filter }, { type: 'start-record' });
const drafts = state.drafts;
state = { ...state, route: 'detail', selected_record_id: 'both' };
state = demoReducer(state, { type: 'explore-color', hex: '#609867' });
assert.equal(state.route, 'book');
assert.equal(state.selected_record_id, null);
assert.equal(state.book_filter.color?.hex, '#609867', 'detail searches its actual extracted shade, not a preset bucket');
assert.equal(state.book_filter.start_date, filter.start_date);
assert.equal(state.book_filter.semantic_tag, filter.semantic_tag);
assert.equal(state.book_filter.favorite_only, true);
assert.equal(state.drafts, drafts, 'browsing preserves the unfinished photo draft');
const applied = state.book_filter;
state = demoReducer(state, { type: 'open-filter' });
state = demoReducer(state, { type: 'sheet-change', change: { kind: 'filter', working: { ...applied, color: createColorSearch('#EF0044') } } });
assert.deepEqual(state.book_filter, applied, 'picking changes only the sheet draft');
state = demoReducer(state, { type: 'sheet-cancel' });
assert.equal(state.sheet, null);
assert.deepEqual(state.book_filter, applied, 'cancel restores the applied color/range/share');
state = demoReducer(state, { type: 'open-filter' });
state = demoReducer(state, { type: 'sheet-change', change: { kind: 'filter', working: { ...applied, color: createColorSearch('#0000FF') } } });
state = demoReducer(state, { type: 'sheet-apply' });
assert.equal(state.book_state, 'filter-empty', 'zero color matches keeps filter controls available');
state = demoReducer(state, { type: 'open-filter' });
state = demoReducer(state, { type: 'sheet-change', change: { kind: 'filter', working: { ...applied, color: null } } });
state = demoReducer(state, { type: 'sheet-apply' });
assert.equal(state.book_filter.color, null);
assert.equal(state.book_filter.semantic_tag, '산책', 'clearing color preserves tag/date/favorite');
state = demoReducer({ ...state, book_filter: filter }, { type: 'open-filter' });
state = demoReducer(state, { type: 'clear-book-filter' });
assert.ok(!Object.values(state.book_filter).some(Boolean), 'All clears color, date, tag and favorite together');
assert.equal(state.sheet, null, 'All cannot leave an old working filter to reapply');
assert.equal(filterRecords(records, state.book_filter).length, records.length, 'All restores records outside the previous filter');
assert.equal(state.drafts, drafts, 'All preserves photo drafts');
const before = state;
assert.equal(demoReducer(before, { type: 'explore-color', hex: 'not-a-color' }), before);
assert.equal(JSON.stringify(records), snapshot, 'no palette, notes, IDs or metadata mutate');
console.log('color-exploration passed: combined filters, summed share, exact detail shade, cancel/apply/clear, filter-empty and draft preservation');
