export const memoCopy = {
  ko: {
    aiTitle: 'AI가 쓴 글',
    directHint: '직접 쓰거나 AI 글을 가져온 뒤 자유롭게 고칠 수 있어요.',
    generationHint: '제안은 가져오기 전까지 메모를 바꾸지 않아요.',
    generate: '글 제안 만들기',
    generating: '글 제안 만드는 중',
    retry: '다시 만들기',
    failed: '글 제안을 만들지 못했어요.',
    import: '메모에 가져오기',
    replacePrompt: '작성 중인 메모를 AI 글로 바꿀까요? 바꾼 뒤 한 번 되돌릴 수 있어요.',
    replace: '메모 바꾸기',
    keep: '현재 메모 유지',
    clear: '메모 비우기',
    restore: '이전 메모 되돌리기',
  },
  en: {
    aiTitle: 'AI writing',
    directHint: 'Write directly, or add the AI writing and edit it freely.',
    generationHint: 'The suggestion will not change your memo until you add it.',
    generate: 'Create writing suggestion',
    generating: 'Creating writing suggestion',
    retry: 'Try again',
    failed: 'Unable to create a writing suggestion.',
    import: 'Add to memo',
    replacePrompt: 'Replace your current memo with the AI writing? You can restore it once afterward.',
    replace: 'Replace memo',
    keep: 'Keep current memo',
    clear: 'Clear memo',
    restore: 'Restore previous memo',
  },
} as const;
