import assert from 'node:assert/strict';
import { canWrapSemantically, nativeBreaks, prepareSemanticWrap, resolveSemanticWrap } from './semantic-wrap.ts';

const text = '더 나은 사용자 경험을 만드는 방법';
assert.equal(canWrapSemantically(text), true);
for (const value of ['', '제목', '직접\n줄바꿈', '공백  보존', ' 앞 공백', '긴 문장 '.repeat(40)]) assert.equal(canWrapSemantically(value), false);
assert.deepEqual(nativeBreaks(text, ['더 나은 사용자 ', '경험을 만드는 방법']), [8]);
assert.equal(nativeBreaks(text, ['다른 문장']), null);
const lines = ['더 나은 사용자 ', '경험을 만드는 방법'];
const input = prepareSemanticWrap(text, lines);
assert.ok(input);
assert.ok(input.samples.includes(text));
assert.ok(input.samples.includes(' '));
assert.ok(input.samples.includes('사용자 경험을'));
const widths = new Map(input.samples.map(value => [value, value.length]));
const result = resolveSemanticWrap(text, lines, 12, widths);
assert.equal(result, text, 'Keep the already balanced native layout.');
assert.equal(result.replaceAll('\n', ' '), text);
const uneven = ['더 나은 사용자 경험을 만드는', '방법'];
assert.equal(resolveSemanticWrap(text, uneven, 17, widths), '더 나은\n사용자 경험을 만드는 방법');
for (const width of [0, NaN, -1]) assert.equal(resolveSemanticWrap(text, lines, width, widths), text);
assert.equal(resolveSemanticWrap(text, lines, 12, new Map()), text);
assert.equal(resolveSemanticWrap(text, lines, 12, new Map(input.samples.map(sample => [sample, NaN]))), text);
assert.equal(resolveSemanticWrap(text, lines, 12, new Map(input.samples.map(sample => [sample, -1]))), text);
assert.equal(resolveSemanticWrap(text, lines, 12, widths, 1), text);
assert.equal(resolveSemanticWrap(text, [text], 100, widths), text);
const KoreanNotice = 'AI 변환 과정에서 일부 윤곽이나 세부 표현이 생략될 수 있어요.';
const splitKoreanNotice = ['AI 변환 과정에서 일부 윤곽이나 세부 표현이 생략될 수 있', '어요.'];
const KoreanNoticeInput = prepareSemanticWrap(KoreanNotice, splitKoreanNotice);
assert.ok(KoreanNoticeInput);
const KoreanNoticeWidths = new Map(KoreanNoticeInput.samples.map(sample => [sample, [...sample].reduce((total, character) => total + (character === ' ' ? 0.35 : 1), 0)]));
assert.equal(resolveSemanticWrap(KoreanNotice, splitKoreanNotice, 29, KoreanNoticeWidths), 'AI 변환 과정에서 일부 윤곽이나\n세부 표현이 생략될 수 있어요.');
const english = 'A familiar place with a new story to remember';
const englishLines = ['A familiar place with a new ', 'story to remember'];
const englishInput = prepareSemanticWrap(english, englishLines);
assert.ok(englishInput);
const englishWidths = new Map(englishInput.samples.map(value => [value, value.length]));
assert.equal(resolveSemanticWrap(english, englishLines, 27, englishWidths).replaceAll('\n', ' '), english);
console.log('PASS: semantic-wrap selection, Korean/English, source preservation and native fallbacks.');
